clumio-code/terraform-clumio-aws-template

README.md, examples/all_data_sources/README.md, examples/all_data_sources/versions.tf, main.tf.json, variables.tf.json, versions.tf.json
Make path as a variable in the module AWS IAM roles, policies and instance profile resources.
Also added path to the policies clumio_ec2_protect_managed_policy and clumio_discover_policy.
=> Make path as a variable in the module AWS IAM roles, policies and instance profile resources

README.md, examples/all_data_sources/main.tf, main.tf.json, variables.tf.json
Changes to include dynamodb resources and also changes related to removing is_warmtier_enabled variable.
Updated README.md and example file also.
=> Changes to include dynamodb resources

main.tf.json
Added the dynamodb check in the properties for post_process_aws_connection
=> Added the dynamodb check in the properties for post_process_aws_connection

CONTRIBUTING.md, examples/all_data_sources/main.tf, examples/all_data_sources/versions.tf, main.tf.json, variables.tf.json, versions.tf.json
=> Consolidated configuration

README.md, main.tf.json
Changes in module resources so that rds is no longer dependent on ebs.
=> Changes in module resources so that rds is no longer dependent on ebs

versions.tf.json
clumio provider required version changed
=> clumio provider required version changed

main.tf.json, versions.tf.json
Updates to ebs, rds and s3 policy document permissions
=> Updates to ebs, rds and s3 policy document permissions

main.tf.json
Added is_dynamodb_enabled check for clumio_iam_role_policy and permissions_boundary resources
=> Added is_dynamodb_enabled check for clumio_iam_role_policy and permissions_boundary resources

versions.tf.json
Updated Clumio Provider version required to ~0.4.0
=> Updated Clumio Provider version required to ~0.4.0

main.tf.json
Removed the unused local variable region_map
=> Removed the unused local variable region_map

main.tf.json, variables.tf.json
dynamodb version updated in post_process_clumio_aws_connection
=> dynamodb version updated in post_process_clumio_aws_connection

main.tf.json, variables.tf.json
Added permissions boundary for clumio roles.
=> Added permissions boundary for clumio roles.

main.tf.json
Updated S3 Protect Policy permissions.
=> Updated S3 Protect Policy permissions.

README.md, main.tf.json, variables.tf.json
Additional IAM policy statement added to dynamodb protect policy.
Also updated the required provider version and other minor changes in the module documentation.
=> Additional IAM policy statement added to dynamodb protect policy.

main.tf.json
=> Fixed a typo.

main.tf.json
Removed the unused aws_canonical_user_id block
=> Removed the unused aws_canonical_user_id block

main.tf.json
updates to s3 discover permissions and ec2-mssql role name
=> updates to s3 discover permissions and ec2-mssql role name

main.tf.json
Permission changes to the dynamodb protect policy.
=> Permission changes to the dynamodb protect policy.

README.md, main.tf.json, variables.tf.json
Updates to s3 permissions and role chaining changes.
=> Updates to s3 permissions and role chaining changes

versions.tf.json
updated required providers version for clumio
=> updated required providers version for clumio

README.md, examples/all_data_sources/main.tf, examples/all_data_sources/provider.tf, examples/all_data_sources/variables.tf, examples/all_data_sources/versions.tf
=> documentation updated

CHANGELOG.md
=> Change log added.

CHANGELOG.md, main.tf.json
Removed the statement AllowS3EventFwdToClumio from the s3_protect_policy
=> Removed the statement AllowS3EventFwdToClumio from the s3_protect_policy

.terraform-docs.yaml, CHANGELOG.md, README.md, main.tf.json, variables.tf.json
Role chaining enabled by default and s3 permissions change
=> Role chaining enabled by default and s3 permissions change

CHANGELOG.md, README.md, main.tf.json
Updates to clumio_ec2_mssql_protect_policy_document
=> Updates to clumio_ec2_mssql_protect_policy_document

CHANGELOG.md, README.md, examples/all_data_sources/README.md, main.tf.json, variables.tf.json
This is a major change in the module which will cause issues to customers while upgrading from previous versions of the module. There are policy name changes, role name changes which will cause existing policies/roles to be deleted and new policies/roles to be created. So while this upgrade is running, any backups which are running will fail. 
Also thorough upgrade testing needs to be done before this can be released.
=> Changes to policies to make it modular which requires changes to all data sources

.terraform-docs.yaml, CHANGELOG.md, README.md, examples/all_data_sources/main.tf, main.tf.json
Updates to RDS restore policy permissions along with documentation updates.
=> Updates to RDS restore policy permissions along with documentation updates.

main.tf.json
Changes to EC2 Mssql and dynamoDB
=> Changes to EC2 Mssql and dynamoDB

CHANGELOG.md
Updated the changelog for v0.21.0
=> Updated the changelog for v0.21.0

versions.tf.json
Update the required version to ~>0.6.0
=> Update the required version to ~>0.6.0

CHANGELOG.md, README.md, versions.tf.json
Changed required version of clumio provider to >=0.5.1, <0.7.0
=> Changed required version of clumio provider to >=0.5.1, <0.7.0

CHANGELOG.md, main.tf.json
RDS Restore policy permissions update
=> RDS Restore policy permissions update

CHANGELOG.md, README.md, examples/all_data_sources/versions.tf, main.tf.json, variables.tf.json, versions.tf.json
New variables wait_for_ingestion and wait_for_data_plane_resources added
=> New variables wait_for_ingestion and wait_for_data_plane_resources added

main.tf, variables.tf
Added variables to add encryption key for Clumio Inventory SNS topic.
=> Added variable to add encryption key for Clumio Inventory SNS topic.

CHANGELOG.md, README.md, examples/all_data_sources/versions.tf, versions.tf
Updated Changelog for the new version and updated the required provider version.
=> Updated Changelog for the new version and updated the required provider version.

main.tf
Updated permissions for RDS backup and restore policies
=> Updated permissions for RDS backup and restore policies

CHANGELOG.md, README.md, common.tf, variables.tf
Changes to key policy permission for kms key associated with ClumioInventory SNS topic
=> Changes to key policy permission for kms key associated with ClumioInventory SNS topic

CHANGELOG.md, common.tf, s3.tf
Update to s3 policy condition.
=> Update to s3 policy condition.

.terraform-docs.yaml, CHANGELOG.md, README.md, common.tf, ebs_ec2.tf, examples/all_data_sources/README.md, examples/all_data_sources/versions.tf, s3.tf
Changes to inventory policy and cloudwatch_event_rule resources for EBS/EC2, S3 and DynamoDB.
Documentation updates corresponding to the above changes.
=> Changes to inventory policy and cloudwatch_event_rule resources for EBS/EC2, S3 and DynamoDB

CHANGELOG.md, README.md, examples/all_data_sources/README.md, examples/all_data_sources/versions.tf, versions.tf
Required provider version updated to >=0.10.0, <0.12.0
=> Required provider version updated to >=0.10.0, <0.12.0

CHANGELOG.md, common.tf, dynamodb.tf, ebs_ec2.tf, rds.tf, s3.tf
Changes to split clumio_aws_backup_cloudwatch_event_rule to data source specific event rules.
=> Changes to split clumio_aws_backup_cloudwatch_event_rule to data source specific event rules.

CHANGELOG.md, common.tf, dynamodb.tf
Inventory and DynamoDB policy permission updates
=> Inventory and DynamoDB policy permission updates

README.md
Documentation update for MSSQLEC2 connections
=> Documentation update for MSSQLEC2 connections

CHANGELOG.md, common.tf, dynamodb.tf, ebs_ec2.tf, ec2_mssql.tf, rds.tf, s3.tf
Summary:
- Add local variable `partition` to avoid hardcoding in .tf file.
- Update config version to 24.3.
- Update DDB version to 7.3 with contributor insights.
- Update EBS version to 25.3 with removing EIA policies.
- Update S3 version to 7.5 with allowing copy from S3 data bucket access point.
=> Update config versions to latest for each asset
